print("witaj użytkowniku, podaj swoje imię: ")
imie = input()
print("miło Cię widzieć",imie)
print("liczba znaków w imieniu:",len(imie))
wiek = int(input("podaj swój wiek: "))
print("Twój wiek:",wiek)
print("Twój wiek za 10 lat:" + str(wiek+10))
cena = float(input("podaj cenę biletu: "))
print("cena biletu z rabatem 10% wynosi:",cena*0.9,"zł")
