-- MySQL Script generated by MySQL Workbench
-- Sun Jan 22 10:36:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekty_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projekty_db` ;

-- -----------------------------------------------------
-- Schema projekty_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekty_db` DEFAULT CHARACTER SET utf8 ;
USE `projekty_db` ;

-- -----------------------------------------------------
-- Table `projekty_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekty_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `projekty_db`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `begin_date` TEXT NOT NULL,
  `end_date` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekty_db`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekty_db`.`tasks` ;

CREATE TABLE IF NOT EXISTS `projekty_db`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `priority` INT NOT NULL,
  `status_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `begin_date` TEXT NOT NULL,
  `end_date` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tasks_projects_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `projekty_db`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
